Repository apache-superset/superset-ui-plugins, pull requests merged in 2019-07, with the labels that each got.

#134 fix: fixing tooltip for expanded area chart
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Area/Stories.jsx
Labels: size/M

#138 docs: adding changelog for 0.10.35
  CHANGELOG.md
Labels: size/S

#141 fix: responsive y-axis on stacked charts
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Area/Stories.jsx
Labels: size/L

#150 fix: disable lint error
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Axis.ts
Labels: size/XS

#148 fix: single y axis bounds
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-legacy-preset-chart-nvd3/src/utils.js
  packages/superset-ui-legacy-preset-chart-nvd3/test/utils.test.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Area/Stories.jsx
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Line/YAxisStories.jsx
Labels: size/M

#159 fix: nvd3 charts break on stateChange dispatch
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
Labels: size/XS
