Repository apache-superset/superset-ui-plugins, pull requests merged in 2019-08, with the labels that each got.

#167 fix: only remove tooltips relating to a single vis
  package.json
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-legacy-preset-chart-nvd3/src/ReactNVD3.js
  packages/superset-ui-legacy-preset-chart-nvd3/src/utils.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Area/Stories.tsx
Labels: size/M

#165 feat: add basic functionality for icicle chart to display static data
  packages/superset-ui-plugin-chart-icicle-event/package.json
  packages/superset-ui-plugin-chart-icicle-event/src/IcicleEventChart.tsx
  packages/superset-ui-plugin-chart-icicle-event/src/IcicleEventViz.tsx
  packages/superset-ui-plugin-chart-icicle-event/src/transformProps.ts
  packages/superset-ui-plugin-chart-icicle-event/src/utils/IcicleEventTreeHelpers.ts
  packages/superset-ui-plugin-chart-icicle-event/test/utils/IcicleEventTreeHelpers.test.ts
  packages/superset-ui-plugin-chart-icicle-event/types/IcicleEventNode.ts
Labels: size/L

#160 build: speed up storybook build
  packages/superset-ui-plugins-demo/.storybook/webpack.config.js
  packages/superset-ui-plugins-demo/package.json
  packages/superset-ui-plugins-demo/storybook/stories/legacy-plugin-chart-country-map/index.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-plugin-chart-map-box/index.js
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/BoxPlot/index.js
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/Line/index.js
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/ScatterPlot/index.js
Labels: size/M

#175 feat: update type for line chart series
  packages/superset-ui-preset-chart-xy/src/Line/Line.tsx
Labels: size/XS

#106 feat(tablevis): add a new tablevis plugin
  packages/superset-ui-plugin-chart-table/README.md
  packages/superset-ui-plugin-chart-table/package.json
  packages/superset-ui-plugin-chart-table/src/Table.tsx
  packages/superset-ui-plugin-chart-table/src/TableFormData.ts
  packages/superset-ui-plugin-chart-table/src/buildQuery.ts
  packages/superset-ui-plugin-chart-table/src/createMetadata.ts
  packages/superset-ui-plugin-chart-table/src/images/thumbnail.png
  packages/superset-ui-plugin-chart-table/src/images/thumbnailLarge.png
  packages/superset-ui-plugin-chart-table/src/index.ts
  packages/superset-ui-plugin-chart-table/src/legacy/index.ts
  packages/superset-ui-plugin-chart-table/src/legacy/transformProps.ts
  packages/superset-ui-plugin-chart-table/src/processColumns.ts
  packages/superset-ui-plugin-chart-table/src/processData.ts
  packages/superset-ui-plugin-chart-table/src/processMetrics.ts
  packages/superset-ui-plugin-chart-table/src/renderer.tsx
  packages/superset-ui-plugin-chart-table/src/transformProps.ts
  packages/superset-ui-plugin-chart-table/src/types.ts
  packages/superset-ui-plugin-chart-table/test/buildQuery.test.ts
  packages/superset-ui-plugin-chart-table/test/processData.test.ts
  packages/superset-ui-plugin-chart-table/test/processMetrics.test.ts
  packages/superset-ui-plugin-chart-table/types/external.d.ts
  packages/superset-ui-plugins-demo/.storybook/webpack.config.js
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/Stories.jsx
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/data.js
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/dataLegacy.js
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/index.js
Labels: reviewable, size/XL

#178 docs: update thumbnails
  packages/superset-ui-plugin-chart-table/src/images/thumbnail.png
  packages/superset-ui-plugin-chart-table/src/images/thumbnailLarge.png
  packages/superset-ui-preset-chart-xy/src/BoxPlot/images/thumbnail.png
  packages/superset-ui-preset-chart-xy/src/BoxPlot/images/thumbnailLarge.png
  packages/superset-ui-preset-chart-xy/src/ScatterPlot/images/thumbnail.png
  packages/superset-ui-preset-chart-xy/src/ScatterPlot/images/thumbnailLarge.png
Labels: #documentation

#179 fix(plugin-chart-table): move react to peerdependency
  packages/superset-ui-plugin-chart-table/package.json
Labels: size/XS

#181 fix(Table): Fixed styling and filtering issues in superset
  packages/superset-ui-plugin-chart-table/src/Table.tsx
  packages/superset-ui-plugin-chart-table/src/index.ts
  packages/superset-ui-plugin-chart-table/src/legacy/index.ts
  packages/superset-ui-plugin-chart-table/src/renderer.tsx
Labels: size/M
