Repository apache-superset/superset-ui-plugins, pull requests merged in 2019-06, with the labels that each got.

#118 new(preset-chart-xy): Support `LegendRenderer` hook
  packages/superset-ui-preset-chart-xy/src/Line/transformProps.ts
Labels: size/XS

#119 fix: move series in front of xy gridlines
  packages/superset-ui-preset-chart-xy/src/BoxPlot/BoxPlot.tsx
  packages/superset-ui-preset-chart-xy/src/Line/Line.tsx
  packages/superset-ui-preset-chart-xy/src/ScatterPlot/ScatterPlot.tsx
Labels: size/XS

#116 fix: ignore disabled series in stacked bar values
  package.json
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-legacy-preset-chart-nvd3/src/utils.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Bar/data.js
  packages/superset-ui-preset-chart-xy/src/encodeable/AbstractEncoder.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Data.ts
Labels: size/XL

#123 docs: add storybook local run instructions
  README.md
Labels: size/S

#124 build: bump @vx dependencies
  packages/superset-ui-legacy-plugin-chart-histogram/package.json
Labels: size/XS

#132 fix: heatmap errors with null data
  packages/superset-ui-legacy-plugin-chart-heatmap/src/Heatmap.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-plugin-chart-heatmap/Stories.jsx
Labels: size/L
