Repository apache-superset/superset-ui-plugins, pull requests merged in 2019-03, with the labels that each got.

#6 fix(legacy-preset-chart-nvd3): redraw markers after legend interaction
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Line/Stories.jsx
  packages/superset-ui-preset-chart-xy/src/Line/transformProps.js
Labels: bug

#9 chore: lint the webpack config file in storybook
  packages/superset-ui-plugins-demo/storybook-config/webpack.config.js
Labels: reviewable

#8 feat(legacy-preset-chart-nvd3): show negative values on bars
  packages/superset-ui-legacy-preset-chart-nvd3/src/utils.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Bar/Stories.jsx
Labels: enhancement

#1 fix: tooltip disappearance and stickiness
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-legacy-preset-chart-nvd3/src/utils.js
Labels: bug

#12 feat: add typescript declaration for external packages
  packages/superset-ui-preset-chart-xy/package.json
  packages/superset-ui-preset-chart-xy/types/@data-ui/theme/index.d.ts
  packages/superset-ui-preset-chart-xy/types/@data-ui/xy-chart/esm/utils/collectScalesFromProps.d.ts
  packages/superset-ui-preset-chart-xy/types/@data-ui/xy-chart/index.d.ts
  packages/superset-ui-preset-chart-xy/types/@vx/legend/index.d.ts
  packages/superset-ui-preset-chart-xy/types/@vx/responsive/index.d.ts
  packages/superset-ui-preset-chart-xy/types/@vx/scale/index.d.ts
  packages/superset-ui-preset-chart-xy/types/external.d.ts
Labels: reviewable

#14 chore: bump version
  package.json
  packages/superset-ui-plugins-demo/package.json
Labels: enhancement, reviewable

#13 feat: add tooltip and layout components for charts
  packages/superset-ui-preset-chart-xy/src/components/ChartFrame.jsx
  packages/superset-ui-preset-chart-xy/src/components/ChartFrame.tsx
  packages/superset-ui-preset-chart-xy/src/components/WithLegend.tsx
  packages/superset-ui-preset-chart-xy/src/components/tooltip/TooltipFrame.tsx
  packages/superset-ui-preset-chart-xy/src/components/tooltip/TooltipTable.tsx
Labels: enhancement, reviewable

#16 chore(histogram): update @data-ui/histogram for better bins
  packages/superset-ui-legacy-plugin-chart-histogram/package.json
  packages/superset-ui-plugins-demo/storybook/stories/legacy-plugin-chart-histogram/Stories.jsx
Labels: enhancement, reviewable

#19 fix: show only necessary tick labels on log scale
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Line/LogStories.jsx
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Line/index.js
Labels: bug, reviewable

#18 fix: dual line chart color consistency for secondary y axis
  packages/superset-ui-legacy-preset-chart-nvd3/src/utils.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/DualLine/Stories.jsx
Labels: bug, reviewable

#21 fix: bar label for many bars and long labels
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-legacy-preset-chart-nvd3/src/utils.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/DistBar/ManyBarStories.jsx
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/DistBar/index.js
Labels: bug, reviewable

#23 fix: make pivot table handle null string
  packages/superset-ui-legacy-plugin-chart-pivot-table/src/PivotTable.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-plugin-chart-pivot-table/Stories.jsx
Labels: #bug

#15 feat: add encodeable utilities for chart
  package.json
  packages/superset-ui-preset-chart-xy/package.json
  packages/superset-ui-preset-chart-xy/src/Line/Encoder.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/AbstractEncoder.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/ChannelEncoder.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/parsers/extractAxis.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/parsers/extractFormat.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/parsers/extractGetter.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/parsers/extractScale.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Axis.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Channel.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Data.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/FieldDef.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Legend.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Scale.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Specification.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/utils/identity.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/utils/isDisabled.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/utils/isEnabled.ts
Labels: #enhancement, reviewable
