Repository apache-superset/superset-ui-plugins, pull requests merged in 2019-11, with the labels that each got.

#247 fix: pass all props to transformProps in LineMulti chart
  packages/superset-ui-legacy-preset-chart-nvd3/src/LineMulti/LineMulti.jsx
Labels: size/S

#246 feat: improve table performance
  packages/superset-ui-plugin-chart-table/src/Table.tsx
  packages/superset-ui-plugin-chart-table/src/components/HTMLRenderer.tsx
  packages/superset-ui-plugin-chart-table/src/getRenderer.tsx
  packages/superset-ui-plugin-chart-table/src/renderer.tsx
Labels: size/L

#253 fix(table): fix sorting, column width calculation, and text wrapping
  packages/superset-ui-plugin-chart-table/src/Table.tsx
  packages/superset-ui-plugin-chart-table/src/getRenderer.tsx
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/Stories.jsx
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/data.js
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/dataLegacy.js
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/generateData.js
Labels: size/M

#255 Fix links to chart plugins in readme
  README.md
Labels: size/XS

#256 fix(table): fix rendering boolean
  packages/superset-ui-plugin-chart-table/src/getRenderer.tsx
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/dataLegacy.js
Labels: size/S

#240 refactor: convert word cloud to full react
  packages/superset-ui-plugin-chart-word-cloud/package.json
  packages/superset-ui-plugin-chart-word-cloud/src/ReactWordCloud.ts
  packages/superset-ui-plugin-chart-word-cloud/src/WordCloud.ts
  packages/superset-ui-plugin-chart-word-cloud/src/WordCloud.tsx
  packages/superset-ui-plugin-chart-word-cloud/src/index.ts
  packages/superset-ui-plugin-chart-word-cloud/src/transformProps.ts
  packages/superset-ui-plugin-chart-word-cloud/test/transformProps.test.ts
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-word-cloud/Stories.tsx
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-word-cloud/data.js
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-word-cloud/index.js
Labels: size/XL

#264 chore: bump @data-ui/xy-chart@^0.0.84
  packages/superset-ui-legacy-preset-chart-big-number/package.json
  packages/superset-ui-legacy-preset-chart-nvd3/package.json
  packages/superset-ui-preset-chart-xy/package.json
Labels: size/XS

#263 feat: add Liechtenstein to country map chart
  packages/superset-ui-legacy-plugin-chart-country-map/src/countries.js
  packages/superset-ui-legacy-plugin-chart-country-map/src/countries/liechtenstein.geojson
Labels: size/S

#180 fix: horizon chart should scroll when overflowing
  packages/superset-ui-legacy-plugin-chart-horizon/src/HorizonChart.css
  packages/superset-ui-legacy-plugin-chart-horizon/src/HorizonChart.jsx
  packages/superset-ui-legacy-plugin-chart-horizon/src/transformProps.js
Labels: size/XS

#269 build: bump build tools
  package.json
  packages/superset-ui-preset-chart-xy/package.json
Labels: size/XS
