Repository apache-superset/superset-ui-plugins, pull requests merged in 2019-09, with the labels that each got.

#189 fix(tablevis): Set proper width for each column
  packages/superset-ui-plugin-chart-table/src/Table.tsx
  packages/superset-ui-plugin-chart-table/src/legacy/transformProps.ts
  packages/superset-ui-plugin-chart-table/src/transformProps.ts
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/Stories.jsx
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/bigData.js
Labels: size/M

#146 build: automate build & launch of storybook
  README.md
  packages/superset-ui-plugins-demo/package.json
Labels: size/XS

#193 fix: remove redundant target from sankey tooltip
  packages/superset-ui-legacy-plugin-chart-sankey/src/Sankey.js
Labels: size/XS

#198 fix(datatable): adding the consideration of cell padding
  packages/superset-ui-plugin-chart-table/src/Table.tsx
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/bigData.js
Labels: size/S

#200 docs: clarify legacy vs non-legacy in README
  README.md
Labels: size/XS

#201 docs: add npm Link documentation for local development
  README.md
Labels: size/M

#203 fix: add typings for @storybook/react
  packages/superset-ui-plugins-demo/package.json
Labels: size/XS

#204 fix: Line not hidden after legend selection
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
Labels: size/S
