Repository apache-superset/superset-ui-plugins, pull requests merged in 2019-10, with the labels that each got.

#233 build(fix storybook): fix storybook lib dep and node version
  .travis.yml
  packages/superset-ui-plugins-demo/package.json
Labels: size/XS

#229 fix(table): TableVis dynamic height enabled
  .travis.yml
  package.json
  packages/superset-ui-legacy-plugin-chart-paired-t-test/src/TTestTable.jsx
  packages/superset-ui-legacy-preset-chart-nvd3/src/LineMulti/LineMulti.jsx
  packages/superset-ui-plugin-chart-icicle-event/src/IcicleEventChart.tsx
  packages/superset-ui-plugin-chart-table/package.json
  packages/superset-ui-plugin-chart-table/src/Table.tsx
  packages/superset-ui-plugin-chart-table/src/renderer.tsx
  packages/superset-ui-plugins-demo/package.json
  packages/superset-ui-plugins-demo/storybook/stories/plugin-chart-table/bigData.js
  packages/superset-ui-preset-chart-xy/package.json
  packages/superset-ui-preset-chart-xy/src/BoxPlot/BoxPlot.tsx
  packages/superset-ui-preset-chart-xy/src/Line/Line.tsx
  packages/superset-ui-preset-chart-xy/src/ScatterPlot/ScatterPlot.tsx
Labels: size/M

#215 fix: adjust world map colors
  packages/superset-ui-legacy-plugin-chart-world-map/src/WorldMap.js
Labels: size/S

#239 build: fix vega-lite dependencies
  package.json
  packages/superset-ui-preset-chart-xy/package.json
Labels: size/XS

#230 feat: add Korea(South) to Country Maps
  packages/superset-ui-legacy-plugin-chart-country-map/src/countries.js
  packages/superset-ui-legacy-plugin-chart-country-map/src/countries/korea.geojson
Labels: size/S

#241 fix(table): fixed performance issue
  packages/superset-ui-plugin-chart-table/package.json
  packages/superset-ui-plugin-chart-table/src/Table.tsx
  packages/superset-ui-plugin-chart-table/src/legacy/transformProps.ts
  packages/superset-ui-plugin-chart-table/src/processColumns.ts
  packages/superset-ui-plugin-chart-table/src/processData.ts
  packages/superset-ui-plugin-chart-table/src/processMetrics.ts
  packages/superset-ui-plugin-chart-table/src/renderer.tsx
  packages/superset-ui-plugin-chart-table/src/transformProps.ts
  packages/superset-ui-plugin-chart-table/test/processData.test.ts
  packages/superset-ui-plugin-chart-table/test/processMetrics.test.ts
Labels: size/L
