Repository apache-superset/superset-ui-plugins, pull requests merged in 2019-04, with the labels that each got.

#40 fix(legacy-preset-chart-nvd3): stacked bar charts labels
  packages/superset-ui-legacy-preset-chart-nvd3/src/utils.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Bar/Stories.jsx
Labels: size/M

#42 fix: remove sticky tooltip when query returns no data in explore view
  packages/superset-ui-legacy-preset-chart-nvd3/src/ReactNVD3.js
Labels: #bug, reviewable, size/XS

#43 chore: rename willUnmount hook to match the name in `superset-ui/chart`
  packages/superset-ui-legacy-preset-chart-nvd3/src/ReactNVD3.js
Labels: size/XS

#45 fix: y-axis bounds for stacked viz types
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
Labels: size/XS

#44 fix: increment the version number
  package.json
Labels: size/XS

#47 fix: use correct number format
  packages/superset-ui-legacy-preset-chart-big-number/src/BigNumber/transformProps.js
Labels: size/XS

#57 fix: list css as side effects
  packages/superset-ui-legacy-plugin-chart-calendar/package.json
  packages/superset-ui-legacy-plugin-chart-chord/package.json
  packages/superset-ui-legacy-plugin-chart-country-map/package.json
  packages/superset-ui-legacy-plugin-chart-event-flow/package.json
  packages/superset-ui-legacy-plugin-chart-force-directed/package.json
  packages/superset-ui-legacy-plugin-chart-heatmap/package.json
  packages/superset-ui-legacy-plugin-chart-histogram/package.json
  packages/superset-ui-legacy-plugin-chart-horizon/package.json
  packages/superset-ui-legacy-plugin-chart-iframe/package.json
  packages/superset-ui-legacy-plugin-chart-map-box/package.json
  packages/superset-ui-legacy-plugin-chart-markup/package.json
  packages/superset-ui-legacy-plugin-chart-paired-t-test/package.json
  packages/superset-ui-legacy-plugin-chart-parallel-coordinates/package.json
  packages/superset-ui-legacy-plugin-chart-partition/package.json
  packages/superset-ui-legacy-plugin-chart-pivot-table/package.json
  packages/superset-ui-legacy-plugin-chart-rose/package.json
  packages/superset-ui-legacy-plugin-chart-sankey/package.json
  packages/superset-ui-legacy-plugin-chart-sunburst/package.json
  packages/superset-ui-legacy-plugin-chart-table/package.json
  packages/superset-ui-legacy-plugin-chart-treemap/package.json
  packages/superset-ui-legacy-plugin-chart-word-cloud/package.json
  packages/superset-ui-legacy-plugin-chart-world-map/package.json
  packages/superset-ui-legacy-preset-chart-big-number/package.json
  packages/superset-ui-legacy-preset-chart-nvd3/package.json
  packages/superset-ui-plugin-chart-word-cloud/package.json
  packages/superset-ui-preset-chart-xy/package.json
Labels: size/M

#58 build: multi-level nesting in storybook
  packages/superset-ui-plugins-demo/.storybook/config.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-plugin-chart-country-map/Stories.jsx
Labels: size/XS

#59 build: allow xy-chart to publish
  packages/superset-ui-legacy-plugin-chart-calendar/package.json
  packages/superset-ui-legacy-plugin-chart-chord/package.json
  packages/superset-ui-legacy-plugin-chart-country-map/package.json
  packages/superset-ui-legacy-plugin-chart-event-flow/package.json
  packages/superset-ui-legacy-plugin-chart-force-directed/package.json
  packages/superset-ui-legacy-plugin-chart-heatmap/package.json
  packages/superset-ui-legacy-plugin-chart-histogram/package.json
  packages/superset-ui-legacy-plugin-chart-horizon/package.json
  packages/superset-ui-legacy-plugin-chart-iframe/package.json
  packages/superset-ui-legacy-plugin-chart-map-box/package.json
  packages/superset-ui-legacy-plugin-chart-markup/package.json
  packages/superset-ui-legacy-plugin-chart-paired-t-test/package.json
  packages/superset-ui-legacy-plugin-chart-parallel-coordinates/package.json
  packages/superset-ui-legacy-plugin-chart-partition/package.json
  packages/superset-ui-legacy-plugin-chart-pivot-table/package.json
  packages/superset-ui-legacy-plugin-chart-rose/package.json
  packages/superset-ui-legacy-plugin-chart-sankey/package.json
  packages/superset-ui-legacy-plugin-chart-sunburst/package.json
  packages/superset-ui-legacy-plugin-chart-table/package.json
  packages/superset-ui-legacy-plugin-chart-treemap/package.json
  packages/superset-ui-legacy-plugin-chart-word-cloud/package.json
  packages/superset-ui-legacy-plugin-chart-world-map/package.json
  packages/superset-ui-legacy-preset-chart-big-number/package.json
  packages/superset-ui-legacy-preset-chart-nvd3/package.json
  packages/superset-ui-plugin-chart-word-cloud/package.json
  packages/superset-ui-preset-chart-xy/package.json
Labels: size/M

#62 chore: create issue_label_bot.yaml
  .github/issue_label_bot.yaml
Labels: size/XS

#65 fix: word cloud import bug
  package.json
  packages/superset-ui-plugin-chart-word-cloud/src/index.ts
Labels: size/XS

#66 feat: improve line chart margin/axis and add buildquery
  package.json
  packages/superset-ui-plugins-demo/.storybook/addons.js
  packages/superset-ui-plugins-demo/package.json
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/Line/stories/basic.tsx
  packages/superset-ui-preset-chart-xy/src/Line/ChartFormData.ts
  packages/superset-ui-preset-chart-xy/src/Line/Line.tsx
  packages/superset-ui-preset-chart-xy/src/Line/buildQuery.ts
  packages/superset-ui-preset-chart-xy/src/Line/index.ts
  packages/superset-ui-preset-chart-xy/src/Line/transformProps.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/AxisAgent.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/ChannelEncoder.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Axis.ts
Labels: reviewable, size/L

#68 fix: line chart does not handle temporal field correctly
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/Line/stories/basic.tsx
  packages/superset-ui-preset-chart-xy/src/Line/Line.tsx
Labels: size/S

#71 feat: make line chart query operate in time series mode
  packages/superset-ui-preset-chart-xy/src/Line/buildQuery.ts
Labels: size/S

#72 feat: update data format returned from query api and add getGroupBys
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/Line/data/data.js
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/Line/data/data2.js
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/Line/stories/missing.tsx
  packages/superset-ui-preset-chart-xy/src/Line/Encoder.ts
  packages/superset-ui-preset-chart-xy/src/Line/Line.tsx
  packages/superset-ui-preset-chart-xy/src/Line/legacy/transformProps.ts
  packages/superset-ui-preset-chart-xy/src/components/ChartLegend.tsx
  packages/superset-ui-preset-chart-xy/src/encodeable/AbstractEncoder.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/ChannelEncoder.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Data.ts
Labels: size/XL

#70 docs: add storybook page for testing query
  packages/superset-ui-plugins-demo/package.json
  packages/superset-ui-plugins-demo/storybook/shared/components/ErrorMessage.tsx
  packages/superset-ui-plugins-demo/storybook/shared/components/Expandable.tsx
  packages/superset-ui-plugins-demo/storybook/shared/components/VerifyCORS.tsx
  packages/superset-ui-plugins-demo/storybook/shared/components/createQueryStory.tsx
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/Line/index.js
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/Line/stories/query.tsx
Labels: size/L

#73 feat: integrate line chart with build query and update typings
  packages/superset-ui-plugins-demo/storybook/stories/preset-chart-xy/Line/stories/query.tsx
  packages/superset-ui-preset-chart-xy/src/Line/Line.tsx
  packages/superset-ui-preset-chart-xy/src/Line/buildQuery.ts
  packages/superset-ui-preset-chart-xy/src/components/ChartLegend.tsx
  packages/superset-ui-preset-chart-xy/src/encodeable/ChannelEncoder.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Channel.ts
Labels: size/L

#67 docs: update documentation for starting storybook
  packages/superset-ui-plugins-demo/README.md
Labels: size/S

#74 fix: lazily create metadata
  packages/superset-ui-preset-chart-xy/src/Line/createMetadata.ts
  packages/superset-ui-preset-chart-xy/src/Line/index.ts
  packages/superset-ui-preset-chart-xy/src/Line/legacy/index.ts
  packages/superset-ui-preset-chart-xy/src/Line/legacy/metadata.ts
  packages/superset-ui-preset-chart-xy/src/Line/metadata.ts
Labels: size/M
