Repository apache-superset/superset-ui-plugins, pull requests merged in 2020-02, with the labels that each got.

#282 fix: Sunburst chart now respects/prefers Metric's D3 Format setting
  packages/superset-ui-legacy-plugin-chart-sunburst/src/Sunburst.js
  packages/superset-ui-legacy-plugin-chart-sunburst/src/transformProps.js
Labels: size/M

#327 feat: support no data within BigNumber viz
  packages/superset-ui-legacy-preset-chart-big-number/src/BigNumber/BigNumber.jsx
  packages/superset-ui-legacy-preset-chart-big-number/src/BigNumber/transformProps.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-big-number/BigNumber/Stories.tsx
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-big-number/BigNumberTotal/Stories.tsx
Labels: size/M

#291 fix: nvd3 tooltip bolding/non-linebreak on ONLY header row
  package.json
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.css
  packages/superset-ui-legacy-preset-chart-nvd3/src/utils.js
Labels: size/XS

#330 feat: customize no data message in nvd3 charts
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.css
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-plugins-demo/storybook/stories/legacy-preset-chart-nvd3/Pie/Stories.tsx
Labels: size/M

#285 fix: Replace unsafe lifecycle methods
  packages/superset-ui-legacy-plugin-chart-paired-t-test/src/TTestTable.jsx
  packages/superset-ui-legacy-preset-chart-nvd3/src/LineMulti/LineMulti.jsx
Labels: size/S

#346 build: fix target browser
  package.json
  packages/superset-ui-preset-chart-xy/package.json
Labels: size/M

#372 fix: add container css for interval type annotation
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.css
  packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js
  packages/superset-ui-legacy-preset-chart-nvd3/src/utils.js
Labels: size/S
