Repository apache-superset/superset-ui-plugins, pull requests merged in 2020-04, with the labels that each got.

#426 fix: compatible with window
  packages/superset-ui-plugins-demo/package.json
Labels: size/XS

#430 refactor: delete deprecated files
  .gitignore
  babel.config.js
  package.json
  packages/superset-ui-plugin-chart-word-cloud/package.json
  packages/superset-ui-preset-chart-xy/package.json
  packages/superset-ui-preset-chart-xy/src/BoxPlot/BoxPlot.tsx
  packages/superset-ui-preset-chart-xy/src/components/legend/DefaultLegend.tsx
  packages/superset-ui-preset-chart-xy/src/components/legend/DefaultLegendGroup.tsx
  packages/superset-ui-preset-chart-xy/src/components/legend/DefaultLegendItem.tsx
  packages/superset-ui-preset-chart-xy/src/components/legend/createRenderLegend.tsx
  packages/superset-ui-preset-chart-xy/src/components/legend/types.ts
  packages/superset-ui-preset-chart-xy/src/components/legend2/createRenderLegend.tsx
  packages/superset-ui-preset-chart-xy/src/encodeable/AbstractEncoder.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/AxisAgent.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/ChannelEncoder.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/createEncoderClass.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/createEncoderSelector.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/parsers/extractFormat.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/parsers/extractGetter.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/parsers/extractScale.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Axis.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Base.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Channel.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/ChannelDef.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Data.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Legend.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Scale.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/types/Specification.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/utils/identity.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/utils/isDisabled.ts
  packages/superset-ui-preset-chart-xy/src/encodeable/utils/isEnabled.ts
  packages/superset-ui-preset-chart-xy/src/index.ts
  packages/superset-ui-preset-chart-xy/src/utils/XYChartLayout.tsx
  packages/superset-ui-preset-chart-xy/src/utils/constants.ts
  packages/superset-ui-preset-chart-xy/src/utils/convertScaleToDataUIScaleShape.ts
  packages/superset-ui-preset-chart-xy/src/utils/createTickLabelProps.ts
  packages/superset-ui-preset-chart-xy/src/utils/createXYChartLayoutWithTheme.ts
  packages/superset-ui-preset-chart-xy/src/utils2/XYChartLayout.tsx
  packages/superset-ui-preset-chart-xy/src/utils2/createTickComponent.tsx
  packages/superset-ui-preset-chart-xy/test/encodeable/parsers/extractGetter.test.ts
  packages/superset-ui-preset-chart-xy/test/index.test.ts
  yarn.lock
Labels: size/XXL

#433 fix: small issues with charts post-migration
  packages/superset-ui-plugin-chart-word-cloud/package.json
  packages/superset-ui-plugin-chart-word-cloud/src/chart/Encoder.ts
  packages/superset-ui-plugin-chart-word-cloud/src/chart/WordCloud.tsx
  packages/superset-ui-preset-chart-xy/package.json
  packages/superset-ui-preset-chart-xy/src/components/BoxPlot/BoxPlot.tsx
  packages/superset-ui-preset-chart-xy/src/components/BoxPlot/Encoder.ts
  packages/superset-ui-preset-chart-xy/src/components/Line/Encoder.ts
  packages/superset-ui-preset-chart-xy/src/components/Line/Line.tsx
  packages/superset-ui-preset-chart-xy/src/components/ScatterPlot/DefaultTooltipRenderer.tsx
  packages/superset-ui-preset-chart-xy/src/components/ScatterPlot/Encoder.ts
  packages/superset-ui-preset-chart-xy/src/components/ScatterPlot/ScatterPlot.tsx
  packages/superset-ui-preset-chart-xy/src/components/legend/DefaultLegend.tsx
  packages/superset-ui-preset-chart-xy/src/components/legend/DefaultLegendGroup.tsx
  packages/superset-ui-preset-chart-xy/src/components/legend/DefaultLegendItem.tsx
  packages/superset-ui-preset-chart-xy/src/components/legend/createRenderLegend.tsx
  packages/superset-ui-preset-chart-xy/src/components/legend/types.ts
  packages/superset-ui-preset-chart-xy/src/utils/XYChartLayout.tsx
  packages/superset-ui-preset-chart-xy/src/utils/computeAxisLayout.ts
  packages/superset-ui-preset-chart-xy/src/utils/convertScaleToDataUIScaleShape.ts
  packages/superset-ui-preset-chart-xy/src/utils/createXYChartLayoutWithTheme.ts
  yarn.lock
Labels: size/L

#436 feat: bump and remove unnecessary dependencies
  package.json
  packages/superset-ui-preset-chart-xy/package.json
  packages/superset-ui-preset-chart-xy/types/@vx/legend/index.d.ts
  packages/superset-ui-preset-chart-xy/types/@vx/responsive/index.d.ts
  packages/superset-ui-preset-chart-xy/types/@vx/scale/index.d.ts
  yarn.lock
Labels: size/L
